package controladores;

public enum TipoSonido {MANTENERBOTON,PULSARBOTON,UNIRSELLAMADA,COLGARLLAMADA,

    RECOGERBUTANITO,



    NOTABAJO,NOTABAJOIMPACTO,

    CVBASE,
    CVATAQUE,
    CVRECIBEDAÑO,
    CVCONORECIBEDAÑO,
    CVCASCORECIBEDAÑO,
    CVPALAATAQUE,
    CVPALARECIBEDAÑO,
    CVMUERTE,

    BONITILLOBASE,
    BONITILLODAÑO,
    BONITILLORECIBEDAÑO,
    BONITILLOMUERE,




    FURGOARRANCANDO,
    FURGOADELANTE,
    FURGOATRAS,
    FURGOATAQUE,
    FURGORECIBEDAÑO,
    FURGOMUERTE
}
