package controladores;

public enum TipoSonido {MANTENERBOTON,PULSARBOTON,UNIRSELLAMADA,COLGARLLAMADA,

    RECOGERBUTANITO,



    NOTABAJO,NOTABAJOIMPACTO,

    CVBASE,
    CVATAQUE,
    CVRECIBEDAÑO,
    CVCONORECIBEDAÑO,
    CVCASCORECIBEDAÑO,
    CVPALAATAQUE,
    CVPALARECIBEDAÑO,
    CVMUERTE,

    BONITILLOBASE,
    BONITILLODAÑO,
    BONITILLORECIBEDAÑO,
    BONITILLOMUERE,


    ORDENADORBASE,
    ORDENADORATAQUE,
    ORDENADORRECIBEDAÑO,
    ORDENADORMUERE,

    ANGINESPAWN,
    ANGINEBASE,
    ANGINEATAQUE,
    ANGINERECIBADAÑO,
    ANGINEMUERTE,



    FURGOARRANCANDO,
    FURGOADELANTE,
    FURGOATRAS,
    FURGOATAQUE,
    FURGORECIBEDAÑO,
    FURGOFUEGO,
    FURGORUEDAPINCHADA,
    FURGOMUERTE
}
